# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Composer cache
      uses: actions/cache@v2
      env:
        cache-name: cache-composer-dependencies
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: 8.0-composer-${{ hashFiles('composer.json') }}

    - name: PHPCS and PHPStan cache
      uses: actions/cache@v2
      env:
        cache-name: cache-test-results
      with:
        path: tests/cache
        # This uses the hash of query-monitor.php in its cache key because Actions doesn't support
        # always pulling in a cache file and simultaneously always updating it, unlike Travis.
        # This way we always pull in a cache file and refresh it with each new version of QM.
        key: 8.0-phpcs-${{ hashFiles('query-monitor.php') }}

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debugging
      run: |
        php --version
        composer --version

    - name: Composer validate
      run: composer validate --strict

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: Run static analysis
      run: |
        composer test:phpstan

    - name: Run code sniffer
      run: |
        composer test:cs
